name: EditorConfig Check Action
description: Runs editorconfig-checker to verify that your files are in harmony with your .editorconfig

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@main

    - name: Run editorconfig-checker
      shell: bash
      run: editorconfig-checker
