name: EditorConfig Check Action
description: Runs editorconfig-checker to verify that all repository files are in harmony with its .editorconfig

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Install editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@main

    - name: Run editorconfig-checker
      shell: bash
      run: editorconfig-checker
