name: Renovate Config Lint Composite Action
description: Runs renovate-config-validator tool to lint Renovate config file

inputs:
  config-file-path:
    description: >-
      Path to the Renovate config
      file – https://docs.renovatebot.com/getting-started/installing-onboarding/#configuration-location
    required: false
    default: .github/renovate.json5

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Lint Renovate Config file
      uses: suzuki-shunsuke/github-action-renovate-config-validator@main
      with:
        config_file_path: ${{ inputs.config-file-path }}
