name: Renovate Config Lint Composite Action
description: Runs renovate-config-validator tool to lint Renovate config file

inputs:
  config-file-path:
    description: >-
      Path to the Renovate config
      file – https://docs.renovatebot.com/getting-started/installing-onboarding/#configuration-location
    required: false
    default: .github/renovate.json5

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Lint Renovate Config file
      uses: suzuki-shunsuke/github-action-renovate-config-validator@b850926b611b1f3d3fe3729776339c217834bf2c # v2.2.0
      with:
        config_file_path: ${{ inputs.config-file-path }}
