name: Renovate Config Lint Composite Action
description: Runs renovate-config-validator tool to lint Renovate config file

inputs:
  config-file-path:
    description: >-
      Path to the Renovate config
      file – https://docs.renovatebot.com/getting-started/installing-onboarding/#configuration-location
    required: false
    default: .github/renovate.json5

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Lint Renovate Config file
      uses: suzuki-shunsuke/github-action-renovate-config-validator@1e1604219a6b38ae9a10aff42a28a3656322c31a # v2.4.1
      with:
        config_file_path: ${{ inputs.config-file-path }}
