name: GitHub Workflows Check Action
description: Runs actionlint tool to check GitHub Workflows YAML files

inputs:
  filter-mode:
    description: Filter mode used by Reviewdog to filter results – https://github.com/reviewdog/reviewdog#filter-mode
    required: false
    default: file
  github-token:
    description: GitHub token, can be read from `secrets.GITHUB_TOKEN`
    required: true
  reporter:
    description: Reporter used by Reviewdog to report results – https://github.com/reviewdog/reviewdog#reporters
    required: false
    default: github-pr-check

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v4.1.5

    - name: Check GitHub Workflows YAML files
      uses: reviewdog/action-actionlint@51bfb044ddaed55059d16f14daedbe05a9937dc1  # v1.45.0
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        fail_on_error: true
        filter_mode: ${{ inputs.filter-mode }}
        level: error
        reporter: ${{ inputs.reporter }}
