name: GitHub Actions Check Action
description: Runs YAML schema validation tool to check GitHub Actions YAML files

inputs:
  file:
    description: >-
      Path to the GitHub Action YAML file(s). Can accept a glob pattern (will validate all matched files).
      Can accept multiple files (or glob patterns) separated by | symbol.
    required: false
    default: .github/actions/**/*.yaml|.github/actions/**/*.yml
  schema:
    description: JSON schema of GitHub Action YAML file
    required: false
    default: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-action.json

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    - name: Check GitHub Actions YAML files
      uses: cardinalby/schema-validator-action@2166123eb256fa40baef7e22ab1379708425efc7 # v3.1.1
      with:
        file: ${{ inputs.file }}
        fileParser: yaml
        fixSchemas: false
        mode: default
        schema: ${{ inputs.schema }}
