name: Renovate Config Check Action
description: Runs renovate-config-validator tool to check Renovate config file

inputs:
  config-file-path:
    description: Path to the Renovate config file – https://docs.renovatebot.com/getting-started/installing-onboarding/#configuration-location
    required: false
    default: .github/renovate.json5

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Check Renovate Config file
      uses: suzuki-shunsuke/github-action-renovate-config-validator@main
      with:
        config_file_path: ${{ inputs.config-file-path }}
