name: Renovate Config Check Action
description: Runs renovate-config-validator tool to check Renovate config file

inputs:
  config-file-path:
    description: >-
      Path to the Renovate config
      file – https://docs.renovatebot.com/getting-started/installing-onboarding/#configuration-location
    required: false
    default: .github/renovate.json5

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    - name: Check Renovate Config file
      uses: suzuki-shunsuke/github-action-renovate-config-validator@main
      with:
        config_file_path: ${{ inputs.config-file-path }}
