name: YAML Lint Composite Action
description: Runs yamllint tool to lint YAML files

inputs:
  filter-mode:
    description: Filter mode used by Reviewdog to filter results – https://github.com/reviewdog/reviewdog#filter-mode
    required: false
    default: file
  github-token:
    description: GitHub token, can be read from `secrets.GITHUB_TOKEN`
    required: true
  reporter:
    description: Reporter used by Reviewdog to report results – https://github.com/reviewdog/reviewdog#reporters
    required: false
    default: github-pr-check

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Lint YAML files
      uses: reviewdog/action-yamllint@8d79c3d034667db2792e328936811ed44953d691 # v1.44.0
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        fail_on_error: true
        filter_mode: ${{ inputs.filter-mode }}
        level: error
        reporter: ${{ inputs.reporter }}
