name: GitHub Workflows Lint Composite Action
description: Runs actionlint tool to lint GitHub Workflows YAML files

inputs:
  filter-mode:
    description: Filter mode used by Reviewdog to filter results – https://github.com/reviewdog/reviewdog#filter-mode
    required: false
    default: file
  github-token:
    description: GitHub token, can be read from `secrets.GITHUB_TOKEN`
    required: true
  reporter:
    description: Reporter used by Reviewdog to report results – https://github.com/reviewdog/reviewdog#reporters
    required: false
    default: github-pr-check

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Lint GitHub Workflows YAML files
      uses: reviewdog/action-actionlint@f00ad0691526c10be4021a91b2510f0a769b14d0 # v1.68.0
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        fail_on_error: true
        filter_mode: ${{ inputs.filter-mode }}
        level: error
        reporter: ${{ inputs.reporter }}
