name: GitHub Workflows Lint Composite Action
description: Runs actionlint tool to lint GitHub Workflows YAML files

inputs:
  filter-mode:
    description: Filter mode used by Reviewdog to filter results – https://github.com/reviewdog/reviewdog#filter-mode
    required: false
    default: file
  github-token:
    description: GitHub token, can be read from `secrets.GITHUB_TOKEN`
    required: true
  reporter:
    description: Reporter used by Reviewdog to report results – https://github.com/reviewdog/reviewdog#reporters
    required: false
    default: github-pr-check

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Lint GitHub Workflows YAML files
      uses: reviewdog/action-actionlint@7eeec1dd160c2301eb28e1568721837d084558ad # v1.57.0
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        fail_on_error: true
        filter_mode: ${{ inputs.filter-mode }}
        level: error
        reporter: ${{ inputs.reporter }}
