name: GitHub Workflows Lint Composite Action
description: Runs actionlint tool to lint GitHub Workflows YAML files

inputs:
  filter-mode:
    description: Filter mode used by Reviewdog to filter results – https://github.com/reviewdog/reviewdog#filter-mode
    required: false
    default: file
  github-token:
    description: GitHub token, can be read from `secrets.GITHUB_TOKEN`
    required: true
  reporter:
    description: Reporter used by Reviewdog to report results – https://github.com/reviewdog/reviewdog#reporters
    required: false
    default: github-pr-check

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Lint GitHub Workflows YAML files
      uses: reviewdog/action-actionlint@15a7a477ab5ab768a41c39b2c53970bf151c73f3 # v1.56.0
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        fail_on_error: true
        filter_mode: ${{ inputs.filter-mode }}
        level: error
        reporter: ${{ inputs.reporter }}
