name: EditorConfig Lint Composite Action
description: Runs editorconfig-checker to verify that all repository files are in harmony with its .editorconfig

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

    - name: Install editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@main

    - name: Run editorconfig-checker
      shell: bash
      run: editorconfig-checker
