name: EditorConfig Lint Composite Action
description: Runs editorconfig-checker to verify that all repository files are in harmony with its .editorconfig

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c # v2.2.0

    - name: Run editorconfig-checker
      shell: bash
      run: editorconfig-checker
