name: EditorConfig Lint Composite Action
description: Runs editorconfig-checker to verify that all repository files are in harmony with its .editorconfig

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Install editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@main

    - name: Run editorconfig-checker
      shell: bash
      run: editorconfig-checker
