name: EditorConfig Lint Composite Action
description: Runs editorconfig-checker to verify that all repository files are in harmony with its .editorconfig

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@51f63319f592f97930c73d9c46184d20bd206393 # v3.0.0

    - name: Run editorconfig-checker
      shell: bash
      run: editorconfig-checker
