name: Continuous Integration Build

on:
  push:
    branches:
      - main

  workflow_dispatch: ~

permissions:
  checks: write
  contents: read

jobs:
  lint-repository-files:
    uses: syskom/ci-cd/.github/workflows/reusable-lint-files.yaml@main
    with:
      lint-editorconfig: true
      lint-github-actions: true
      lint-github-workflows: true
      lint-renovate-config: true
