name: Continuous Integration Build

on:
  push:
    branches:
      - main

  workflow_dispatch: ~

jobs:
  lint-repository-files:
    name: Lint all files
    uses: syskom/ci-cd/.github/workflows/reusable-lint-files.yaml@main
    permissions:
      checks: write
      contents: read
    with:
      lint-editorconfig: true
      lint-github-actions: true
      lint-github-workflows: true
      lint-renovate-config: true
      lint-yaml-file: true
