name: Continuous Integration Build

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

  workflow_dispatch: ~


# https://docs.github.com/en/actions/using-jobs/using-concurrency https://stackoverflow.com/a/72408109/16358266
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-repository-files:
    name: Lint all files
    uses: syskom/ci-cd/.github/workflows/reusable-lint-files.yaml@main
    permissions:
      checks: write
      contents: read
    with:
      lint-editorconfig: true
      lint-github-actions: true
      lint-github-workflows: true
      lint-renovate-config: true
      lint-yaml-files: true
