name: Continuous Integration Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  changes:
    name: Detect changed files
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      editorconfig: ${{ steps.filter.outputs.editorconfig }}
      github-workflows: ${{ steps.filter.outputs.github-workflows }}
      renovate-config: ${{ steps.filter.outputs.renovate-config }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            editorconfig:
              - ".editorconfig"
            github-workflows:
              - ".github/workflows/*.yaml"
              - ".github/workflows/*.yml"
            renovate-config:
              - ".github/renovate.json5"

  editorconfig-check:
    name: Check EditorConfig file
    needs: changes
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/editorconfig-check@main
        if: needs.changes.outputs.editorconfig == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  github-actions-check:
    name: Check GitHub Workflows YAML files
    needs: changes
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/workflows-check@main
        if: needs.changes.outputs.github-workflows == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  renovate-config-check:
    name: Check Renovate Config file
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/renovate-config-check@main
        if: needs.changes.outputs.renovate-config == 'true'

  # Pseudo-job which does nothing on its own, but serves the purpose of
  # grouping jobs together. In effect, the jobs listed below `needs` are the
  # jobs that are required to pass in order for the whole workflow run to pass.
  branch-protection:
    name: Branch protection job
    runs-on: ubuntu-latest
    needs:
      - editorconfig-check
      - github-actions-check
      - renovate-config-check
    steps:
      - name: Branch protection rule
        run: |
          echo "All needed jobs were successfully executed."
