name: Continuous Integration Checks

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch: ~

# https://docs.github.com/en/actions/using-jobs/using-concurrency https://stackoverflow.com/a/72408109/16358266
concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changed files
    # Set job outputs to values from filter step
    outputs:
      github-actions: ${{ steps.filter.outputs.github-actions }}
      github-workflows: ${{ steps.filter.outputs.github-workflows }}
      renovate-config: ${{ steps.filter.outputs.renovate-config }}
      yaml-files: ${{ steps.filter.outputs.yaml-files }}
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            github-actions:
              - ".github/actions/**/*.yaml"
            github-workflows:
              - ".github/workflows/*.yaml"
            renovate-config:
              - ".github/renovate.json5"
            yaml-files:
              - ".github/actions/**/*.yaml"
              - ".github/workflows/*.yaml"
              - ".yamllint.yaml"

  lint-repository-files:
    name: Lint changed files
    uses: syskom/ci-cd/.github/workflows/reusable-lint-files.yaml@main
    needs: changes
    permissions:
      checks: write
      contents: read
      pull-requests: write
    with:
      lint-editorconfig: true
      lint-github-actions: ${{ needs.changes.outputs.github-actions == 'true' }}
      lint-github-workflows: ${{ needs.changes.outputs.github-workflows == 'true' }}
      lint-github-workflows-filter-mode: file
      lint-github-workflows-reporter: github-pr-check
      lint-renovate-config: ${{ needs.changes.outputs.renovate-config == 'true' }}
      lint-yaml-files: ${{ needs.changes.outputs.yaml-files == 'true' }}
      lint-yaml-files-filter-mode: file
      lint-yaml-files-reporter: github-pr-check

  # This job does nothing and is only used for the branch protection
  all-required-green:
    name: Check if all required jobs succeeded
    if: ${{ !cancelled() }}
    needs:
      - lint-repository-files
    runs-on: ubuntu-latest
    steps:
      - name: Check whether the required jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
