name: Continuous Integration Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  changes:
    name: Detect changed files
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      github-workflows: ${{ steps.filter.outputs.github-workflows }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            github-workflows:
              - ".github/workflows/*.yaml"
              - ".github/workflows/*.yml"

  github-actions-check:
    name: Check GitHub Workflows YAML files
    needs: changes
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/workflows-check@main
        if: needs.changes.outputs.github-workflows == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Pseudo-job which does nothing on its own, but serves the purpose of
  # grouping jobs together. In effect, the jobs listed below `needs` are the
  # jobs that are required to pass in order for the whole workflow run to pass.
  branch-protection:
    name: Branch protection job
    runs-on: ubuntu-latest
    needs:
      - github-actions-check
    steps:
      - name: Branch protection rule
        run: |
          echo "All needed jobs were successfully executed."
