name: Continuous Integration Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  changes:
    name: Detect changed files
    # Set job outputs to values from filter step
    outputs:
      github-actions: ${{ steps.filter.outputs.github-actions }}
      github-workflows: ${{ steps.filter.outputs.github-workflows }}
      renovate-config: ${{ steps.filter.outputs.renovate-config }}
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            github-actions:
              - ".github/actions/**/*.yaml"
            github-workflows:
              - ".github/workflows/*.yaml"
              - ".github/workflows/*.yml"
            renovate-config:
              - ".github/renovate.json5"

  editorconfig-check:
    name: Run EditorConfig Action
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/editorconfig-check@main

  github-actions-check:
    name: Check GitHub Actions YAML files
    if: needs.changes.outputs.github-actions == 'true'
    needs: changes
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/github-actions-check@main

  github-workflows-check:
    name: Check GitHub Workflows YAML files
    if: needs.changes.outputs.github-workflows == 'true'
    needs: changes
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/github-workflows-check@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  renovate-config-check:
    name: Check Renovate Config file
    if: needs.changes.outputs.renovate-config == 'true'
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/renovate-config-check@main

  # This job does nothing and is only used for the branch protection
  all-required-green:
    name: Check if all required checks succeeded
    if: always()
    needs:
      - editorconfig-check
      - github-actions-check
      - github-workflows-check
      - renovate-config-check
    runs-on: ubuntu-latest
    steps:
      - name: Check whether the required jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          allowed-skips: >-
            github-actions-check,
            github-workflows-check,
            renovate-config-check,
          jobs: ${{ toJSON(needs) }}
