name: Continuous Integration Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  changes:
    name: Detect changed files
    # Set job outputs to values from filter step
    outputs:
      github-actions: ${{ steps.filter.outputs.github-actions }}
      github-workflows: ${{ steps.filter.outputs.github-workflows }}
      renovate-config: ${{ steps.filter.outputs.renovate-config }}
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        id: filter
        with:
          filters: |
            github-actions:
              - ".github/actions/**/*.yaml"
            github-workflows:
              - ".github/workflows/*.yaml"
              - ".github/workflows/*.yml"
            renovate-config:
              - ".github/renovate.json5"

  lint-repository-files:
    name: Lint changed files
    uses: syskom/ci-cd/.github/workflows/reusable-lint-files.yaml@main
    needs: changes
    permissions:
      checks: write
      contents: read
      pull-requests: write
    with:
      github-workflows-filter-mode: file
      github-workflows-reporter: github-pr-check
      lint-editorconfig: true
      lint-github-actions: ${{ needs.changes.outputs.github-actions == 'true' }}
      lint-github-workflows: ${{ needs.changes.outputs.github-workflows == 'true' }}
      lint-renovate-config: ${{ needs.changes.outputs.renovate-config == 'true' }}

  # This job does nothing and is only used for the branch protection
  all-required-green:
    name: Check if all required jobs succeeded
    if: always()
    needs:
      - lint-repository-files
    runs-on: ubuntu-latest
    steps:
      - name: Check whether the required jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe  # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
