# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      lint-editorconfig:
        description: >-
          Should run EditorConfig Lint Composite Action to verify that all repository files are in harmony
          with its .editorconfig file.
        required: false
        default: false
        type: boolean
      lint-github-actions:
        description: Should run GitHub Actions Lint Composite Action to lint GitHub Actions YAML files.
        required: false
        default: false
        type: boolean
      lint-github-actions-file:
        description: Path to the GitHub Action YAML file(s) used by GitHub Actions Lint Composite Action.
        required: false
        default: .github/actions/**/*.yaml|.github/actions/**/*.yml
        type: string
      lint-github-actions-schema:
        description: Path to the GitHub Action YAML file schema used by GitHub Actions Lint Composite Action.
        required: false
        default: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-action.json
        type: string
      lint-github-workflows:
        description: Should run GitHub Workflows Lint Composite Action to lint GitHub Workflows YAML files.
        required: false
        default: false
        type: boolean
      lint-github-workflows-filter-mode:
        description: >-
          Filter mode used by Reviewdog in GitHub Workflows Lint Composite Action to filter
          results – https://github.com/reviewdog/reviewdog#filter-mode.
        required: false
        default: nofilter
        type: string
      lint-github-workflows-reporter:
        description: >-
          Reporter used by Reviewdog in GitHub Workflows Lint Composite Action to report
          results – https://github.com/reviewdog/reviewdog#reporters.
        required: false
        default: github-check
        type: string
      lint-renovate-config:
        description: Should run Renovate Config Lint Composite Action to lint Renovate config file.
        required: false
        default: false
        type: boolean
      lint-renovate-config-file-path:
        description: >-
          Path to the Renovate config
          file – https://docs.renovatebot.com/getting-started/installing-onboarding/#configuration-location.
        required: false
        default: .github/renovate.json5
        type: string
      lint-yaml-files:
        description: Should run YAML Lint Composite Action to lint YAML files.
        required: false
        default: false
        type: boolean
      lint-yaml-files-filter-mode:
        description: >-
          Filter mode used by Reviewdog in YAML Lint Composite Action to filter
          results – https://github.com/reviewdog/reviewdog#filter-mode.
        required: false
        default: nofilter
        type: string
      lint-yaml-files-reporter:
        description: >-
          Reporter used by Reviewdog in YAML Lint Composite Action to report
          results – https://github.com/reviewdog/reviewdog#reporters.
        required: false
        default: github-check
        type: string
    outputs:
      editorconfig-lint-result:
        description: The result of lint-editorconfig-job.
        value: ${{ fromJSON(toJSON(jobs.lint-editorconfig-job)).result }}
      github-actions-lint-result:
        description: The result of lint-github-actions-job.
        value: ${{ fromJSON(toJSON(jobs.lint-github-actions-job)).result }}
      github-workflows-lint-result:
        description: The result of lint-github-workflows-job.
        value: ${{ fromJSON(toJSON(jobs.lint-github-workflows-job)).result }}
      renovate-config-lint-result:
        description: The result of lint-renovate-config-job.
        value: ${{ fromJSON(toJSON(jobs.lint-renovate-config-job)).result }}
      workflow-result:
        description: The final result of the workflow.
        value: ${{ fromJSON(toJSON(jobs.workflow-result-job)).result }}
      yaml-files-lint-result:
        description: The result of lint-yaml-files-job.
        value: ${{ fromJSON(toJSON(jobs.lint-yaml-files-job)).result }}

jobs:
  lint-editorconfig-job:
    if: inputs.lint-editorconfig
    name: Run EditorConfig Action
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/editorconfig-lint@main

  lint-github-actions-job:
    if: inputs.lint-github-actions
    name: Lint GitHub Actions YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/github-actions-lint@main
        with:
          file: ${{ inputs.lint-github-actions-file }}
          schema: ${{ inputs.lint-github-actions-schema }}

  lint-github-workflows-job:
    if: inputs.lint-github-workflows
    name: Lint GitHub Workflows YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/github-workflows-lint@main
        with:
          filter-mode: ${{ inputs.lint-github-workflows-filter-mode }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ inputs.lint-github-workflows-reporter }}

  lint-renovate-config-job:
    if: inputs.lint-renovate-config
    name: Lint Renovate Config file
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/renovate-config-lint@main
        with:
          config-file-path: ${{ inputs.lint-renovate-config-file-path }}

  lint-yaml-files-job:
    if: inputs.lint-yaml-files
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: syskom/ci-cd/.github/actions/yaml-lint@main
        with:
          filter-mode: ${{ inputs.lint-yaml-files-filter-mode }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ inputs.lint-yaml-files-reporter }}

  workflow-result-job:
    name: Determine the result of the workflow
    if: ${{ !cancelled() }}
    needs:
      - lint-editorconfig-job
      - lint-github-actions-job
      - lint-github-workflows-job
      - lint-renovate-config-job
      - lint-yaml-files-job
    runs-on: ubuntu-latest
    steps:
      - name: Determine the result of the workflow based on the result of run linting jobs
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          allowed-skips: >-
            lint-editorconfig-job,
            lint-github-actions-job,
            lint-github-workflows-job,
            lint-renovate-config-job,
            lint-yaml-files-job,
          jobs: ${{ toJSON(needs) }}
