# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      add-gradle-job-summary-as-pr-comment:
        description: >-
          Add Gradle Job Summary data as a Pull Request comment. Valid values are "never" (default), "always",
          and "on-failure". Note that to add a Pull Request comment, the workflow must be configured with
          the pull-requests: write permission. See
          https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#adding-job-summary-as-a-pull-request-comment
        required: false
        default: never
        type: string
      java-distribution:
        description: Which Java distribution to use – https://github.com/actions/setup-java#supported-distributions.
        required: false
        default: temurin
        type: string
      java-version:
        description: Which Java version to use – https://github.com/actions/setup-java#supported-version-syntax.
        required: false
        default: 21
        type: string
      run-sonar-scan:
        description: Should run SonarCloud scan.
        required: false
        default: false
        type: boolean
      sonar-timeout-seconds:
        description: >-
          The number of seconds that the build should wait for a report to be processed. The default is 300 seconds.
        required: false
        default: 300
        type: number
    secrets:
      SONAR_TOKEN:
        required: false
        description: The token for authenticating to SonarCloud

defaults:
  run:
    shell: bash

jobs:
  gradle-check:
    name: Run Gradle check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          check-latest: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d9336dac04dea2507a617466bc058a3def92b18b # v3.4.0
        with:
          add-job-summary-as-pr-comment: ${{ inputs.add-gradle-job-summary-as-pr-comment }}
          gradle-version: wrapper
          validate-wrappers: true

      - name: Execute Gradle 'check' task
        run: |
          ./gradlew check --info

      - name: Execute Gradle 'sonar' task
        if: ${{ inputs.run-sonar-scan }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew \
          -Dsonar.qualitygate.timeout=${{ inputs.sonar-timeout-seconds }} \
          -Dsonar.qualitygate.wait=true \
          sonar --info

      - name: Cleanup Gradle Daemons
        run: ./gradlew --stop
