on:
  workflow_call:
    inputs:
      java-distribution:
        description: Which Java distribution to use – https://github.com/actions/setup-java#supported-distributions.
        required: false
        default: temurin
        type: string
      java-version:
        description: Which Java version to use – https://github.com/actions/setup-java#supported-version-syntax.
        required: false
        default: 21
        type: string
      run-sonar-scan:
        description: Should run SonarCloud scan.
        required: false
        default: false
        type: boolean
      sonar-timeout-seconds:
        description: >-
          The number of seconds that the build should wait for a report to be processed. The default is 300 seconds.
        required: false
        default: 300
        type: number
    secrets:
      SONAR_TOKEN:
        required: false
        description: The token for authenticating to SonarCloud

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pull-requests: write  # required by gradle/actions/setup-gradle to add job summary

jobs:
  gradle-check:
    name: Run Gradle check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          check-latest: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # v3.3.2
        with:
          add-job-summary-as-pr-comment: on-failure
          gradle-version: wrapper
          validate-wrappers: true

      - name: Execute Gradle 'check' task
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew check --info

      - name: Execute Gradle 'sonar' task
        if: ${{ inputs.run-sonar-scan }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew \
          -Dsonar.qualitygate.timeout=${{ inputs.sonar-timeout-seconds }} \
          -Dsonar.qualitygate.wait=true \
          sonar --info
